spring.application.name=taskmanager

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/task_manager_db
spring.datasource.username=springuser
spring.datasource.password=Spring@2024
server.port=8081
# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true