name: Docker CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 🔥 STEP 1 — Checkout code (VERY IMPORTANT)
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🔥 STEP 2 — Verify files
      - name: List files
        run: ls -la

      # 🔥 STEP 3 — Just test
      - name: Print Hello
        run: echo "Pipeline is working 🚀"
